// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzmZqSpu5OW0hE2Ouqtllf2MXIGqxL5dk',
    appId: '1:985184859718:web:dff36b1ead0adce4f9fc47',
    messagingSenderId: '985184859718',
    projectId: 'let-schat-7db7a',
    authDomain: 'let-schat-7db7a.firebaseapp.com',
    storageBucket: 'let-schat-7db7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqyLnlJtJz-t5t2pg9cdbn-mQHA8c7KI',
    appId: '1:985184859718:android:b0a0b36ada0a6154f9fc47',
    messagingSenderId: '985184859718',
    projectId: 'let-schat-7db7a',
    storageBucket: 'let-schat-7db7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWYwAU1fK6nu5aE3Ifi22UYhlOqcWzXMY',
    appId: '1:985184859718:ios:1422a5f362ccb5ccf9fc47',
    messagingSenderId: '985184859718',
    projectId: 'let-schat-7db7a',
    storageBucket: 'let-schat-7db7a.appspot.com',
    iosClientId: '985184859718-a9m0bt7o502vuspa364753r2a08tuvd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApplicatrion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWYwAU1fK6nu5aE3Ifi22UYhlOqcWzXMY',
    appId: '1:985184859718:ios:1422a5f362ccb5ccf9fc47',
    messagingSenderId: '985184859718',
    projectId: 'let-schat-7db7a',
    storageBucket: 'let-schat-7db7a.appspot.com',
    iosClientId: '985184859718-a9m0bt7o502vuspa364753r2a08tuvd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApplicatrion',
  );
}
